# Generated by Django 5.2.4 on 2025-07-22 21:31

import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=inventory.models.product_image_upload_path),
        ),
    ]
